services:
  lakehouse_storage:
    image: minio/minio
    container_name: lakehouse_storage
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address ':9001' & 
      until curl -sf http://localhost:9000/minio/health/live; do sleep 1; done;
      mc alias set local http://localhost:9000 admin 12345678;
      mc mb --ignore-existing local/lakehouse;
      wait
      "
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      aws_molpay:

  lakehouse_catalog:
    image: tabulario/iceberg-rest
    container_name: lakehouse_catalog
    ports:
      - "8585:8181"
    environment:
      - CATALOG_WAREHOUSE=s3a://lakehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://lakehouse_storage:9000
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=12345678
      - AWS_REGION=ap-southeast-1
    networks:
      aws_molpay:

networks:
  aws_molpay:
    external: true